name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set Go version
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'
      - name: "Build"
        run: ./build.sh
        shell: bash

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            dist/*
