name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Go version
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'

      - name: "Build"
        run: ./build.sh
        shell: bash

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          excludeTypes: build,docs,other,style,chore

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          makeLatest: true
          body: ${{ steps.changelog.outputs.changes }}
          files: |
            dist/fab-gem-id-importer_darwin-amd64.app
            dist/fab-gem-id-importer_darwin-arm64.app
            dist/fab-gem-id-importer_linux-arm64
            dist/fab-gem-id-importer_linux-arm64
            dist/fab-gem-id-importer_windows-arm64.exe
            dist/fab-gem-id-importer_windows-arm64.exe
