name: Launch tests
on:
  push:
    branches:
      - "main"

jobs:
  launch-tests:
    name: "Launch tests"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set Go version
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'
      - name: "Test"
        run: go test ./...
